#!/usr/bin/env bash
# A Bash script that displays lines containing the word "bash" from the process list
# shellcheck disable=$C2009

ps -eo user, pid, %cpu, %mem,vsz,rss,tty,stat,time,command --forest | grep bash 
